### ISSUE TITLE
Posible error en la linea 35 y 36 de Motor.cpp

### ISSUE THREAD

**Issue by Jamesscn** [LionsRoboticsClub/GeneralRobot#1]
Si deciden correr **Motor::move(0)** despues de correr a move con un valor negativo lo mas probable es que el robot siga retrocediendo en lugar de pararse completamente. Esto pasaría porque en las lineas 35 y 36 de Motor.cpp modifican el pin de avance dos veces en lugar del pin de avance y el pin de retroceso una sola vez:

```
analogWrite(_pinFwd, 0);
analogWrite(_pinFwd, 0);
```

Sugiero que cambien _pinFwd a _pinBwd en la segunda línea:

```
analogWrite(_pinFwd, 0);
analogWrite(_pinBwd, 0);
```

**Comment by pcruiher08** [comment]
Gracias James, ya subí la corrección.
